### ISSUE TITLE
Install phantom.js for running tests

### ISSUE THREAD

**Issue by mathuin** [pono/pgd_cookbook#4]
https://supermarket.getchef.com/cookbooks/phantomjs

This should let us run our selenium tests in a headless format.

**Comment by pono** [comment]
Pull requests welcome ;)
Do you want anything besides it to be installed?

**Comment by mathuin** [comment]
That's about it.  I hadn't thought about sending pull requests, to be honest, and I probably can do that for most of the issues I've submitted.  Duh.
